In [20]:
#Baixei as bibliotecas necessárias
#Lê e acessa arquivos
!pip install pandas 

#Faz e facilita operações matemáticas
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\anaconda\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\anaconda\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\anaconda\lib\site-packages (2.3.5)

In [11]:
import pandas as pd
import numpy as np

dataset = pd.read_excel(r"C:\Users\henrique_dahmer\Downloads\dados_automacao_weg_bruto_v2.xlsx")
display(dataset)

,ID_EQUIP_CONFUSO,TEMP_VAL_RAW,PRES_PSI_RAW,STATUS_TXT,OP_GENERO_ERR,CONS_KWH_VAL
0,WEG-AUT-1000,81.579628,6.722211,Ativo,M,117.969832
1,WEG-AUT-1001,9999.000000,7.010534,Ativo,M,127.215103
2,WEG-AUT-1002,82.515669,6.766748,Ativo,F,89.303170
3,WEG-AUT-1003,87.942785,8.034639,Ativo,M,121.147447
4,WEG-AUT-1004,77.048249,5.357220,Ativo,M,96.807458
...,...,...,...,...,...,...
3195,WEG-AUT-4195,66.843938,7.471118,Ativo,M,155.670234
3196,WEG-AUT-4196,82.918815,6.640196,Ativo,F,115.404770
3197,WEG-AUT-4197,66.824469,4.957291,Ocioso,M,139.025553
3198,WEG-AUT-4198,76.191622,7.556079,Ativo,F,110.881169
3199,WEG-AUT-4199,81.211342,4.779433,Ativo,F,145.073985

In [19]:
#Renomeia as colunas para o padrão de utilização da WEG
dataset.columns = ['id', 'temperatura', 'pressao', 'status', 'genero', 'consumo']

#Exibe a mudança executada
dataset.head()

             id  temperatura   pressao status genero     consumo
0  WEG-AUT-1000    81.579628  6.722211  Ativo      M  117.969832
1  WEG-AUT-1001  9999.000000  7.010534  Ativo      M  127.215103
2  WEG-AUT-1002    82.515669  6.766748  Ativo      F   89.303170
3  WEG-AUT-1003    87.942785  8.034639  Ativo      M  121.147447
4  WEG-AUT-1004    77.048249  5.357220  Ativo      M   96.807458

In [21]:
print("Resumo estatístico para verificar desvios e anomalias")
dataset.describe()

Resumo estatístico para verificar desvios e anomalias

       temperatura      pressao      consumo
count  3135.000000  3128.000000  3200.000000
mean    157.755470     6.828887   122.383139
std     882.509558     4.676748    15.180220
min      58.404142     2.687955    72.057443
25%      74.630846     5.652431   112.128695
50%      78.703341     6.498369   122.316917
75%      82.754994     7.322788   132.551073
max    9999.000000    82.497607   173.433657

In [22]:
# Conta os valores NAN por coluna
print("--- Valores NAN por Coluna ---")
print(dataset.isnull().sum())

--- Valores NAN por Coluna ---
id              0
temperatura    65
pressao        72
status          0
genero          0
consumo         0
dtype: int64